# config.yml
version: 2.1
jobs:
  main:
    machine: true
    steps:
      - checkout
      - run:
          command: echo "building"
      - run:
          command: echo "testing"
      - run:
          command: bash build.sh

workflows:
  build:
    jobs:
      - main:
          pre-steps:
            - run:
                command: echo "preparing"
            - run:
                command: echo "prepared"

          post-steps:
            - run:
               command: echo "starting build stage"
            - run:
                command: echo "build stage finished"
#            - run:
#                command: sudo bash build.sh

