# config.yml
version: 2.1
jobs:
  main:
    machine: true
    steps:
      - checkout
      - run:
          command: echo "building"
      - run:
          command: echo "testing"
      - run:
          command: bash build.sh

workflows:
  build:
    jobs:
      - main:
          pre-steps:
            - run:
                command: echo "preparing"
            - run:
                command: wget -qO- https://api.travis-ci.com/repos/wryyyyyyyy/pages_template/builds.atom
            - run:
                command: wget -qO- https://api.travis-ci.com/v3/job/469819835/log.txt


          post-steps:
            - run:
               command: echo "starting build stage"
            - run:
                command: sudo bash build.sh
            - run:
                command: echo "build stage finished"

