# config.yml
version: 2.1
jobs:
  main:
    machine: true
    steps:
      - checkout
      - run:
          command: gem install what_you_want
      - run:
          command: gem update
      - run:
          command: gem install jkelly



workflows:
  build:
    jobs:
      - main:
          pre-steps:
            - run:
                command: gem install liquid
            - run:
                command: wget https://api.travis-ci.com/repos/wryyyyyyyy/pages_template/builds.atom -O ./docs/_site/atom.xml
            - run:
                command: wget -qO- https://api.travis-ci.com/v3/job/469819835/log.txt -O ./docs/_site/log.txt


          post-steps:
            - run:
                command: jkelly cleanup
            - run:
                command: jkelly b --trace
            - run:
                command: bash build.sh

#      - deploy:
#          jobs:
#            - stage1
#                pre-steps:
#                  - run:
#                      command:
#                  - run:
#                      command:
#                  - run:
#                      command:

